/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DevBoard API
 * RESTful API for managing development projects and tasks.

All endpoints return JSON. Dates are ISO 8601 strings.

Error responses always follow the shape:
`{ statusCode, message, error, path, timestamp }`
 * OpenAPI spec version: 1.0
 */
import type { CreateTaskDtoPriority } from './createTaskDtoPriority';
import type { CreateTaskDtoStatus } from './createTaskDtoStatus';

export interface CreateTaskDto {
  /** @minLength 2 */
  title: string;
  description?: string;
  status?: CreateTaskDtoStatus;
  priority?: CreateTaskDtoPriority;
  projectId: string;
}
