/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DevBoard API
 * RESTful API for managing development projects and tasks.

All endpoints return JSON. Dates are ISO 8601 strings.

Error responses always follow the shape:
`{ statusCode, message, error, path, timestamp }`
 * OpenAPI spec version: 1.0
 */
import type { GetHealth503Details } from './getHealth503Details';
import type { GetHealth503Error } from './getHealth503Error';
import type { GetHealth503Info } from './getHealth503Info';

export type GetHealth503 = {
  status?: string;
  /** @nullable */
  info?: GetHealth503Info;
  /** @nullable */
  error?: GetHealth503Error;
  details?: GetHealth503Details;
};
