/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DevBoard API
 * RESTful API for managing development projects and tasks.

All endpoints return JSON. Dates are ISO 8601 strings.

Error responses always follow the shape:
`{ statusCode, message, error, path, timestamp }`
 * OpenAPI spec version: 1.0
 */
import type { GetHealth200Details } from './getHealth200Details';
import type { GetHealth200Error } from './getHealth200Error';
import type { GetHealth200Info } from './getHealth200Info';

export type GetHealth200 = {
  status?: string;
  /** @nullable */
  info?: GetHealth200Info;
  /** @nullable */
  error?: GetHealth200Error;
  details?: GetHealth200Details;
};
