/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DevBoard API
 * RESTful API for managing development projects and tasks.

All endpoints return JSON. Dates are ISO 8601 strings.

Error responses always follow the shape:
`{ statusCode, message, error, path, timestamp }`
 * OpenAPI spec version: 1.0
 */
import type { TaskResponseDtoPriority } from './taskResponseDtoPriority';
import type { TaskResponseDtoStatus } from './taskResponseDtoStatus';

export interface TaskResponseDto {
  id: string;
  /** @minLength 2 */
  title: string;
  description?: string;
  status: TaskResponseDtoStatus;
  priority: TaskResponseDtoPriority;
  projectId: string;
  createdAt: string;
  updatedAt: string;
}
