/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DevBoard API
 * RESTful API for managing development projects and tasks.

All endpoints return JSON. Dates are ISO 8601 strings.

Error responses always follow the shape:
`{ statusCode, message, error, path, timestamp }`
 * OpenAPI spec version: 1.0
 */

export type UpdateProjectDtoStatus =
  (typeof UpdateProjectDtoStatus)[keyof typeof UpdateProjectDtoStatus];

export const UpdateProjectDtoStatus = {
  active: 'active',
  completed: 'completed',
  archived: 'archived',
} as const;
