/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DevBoard API
 * RESTful API for managing development projects and tasks.

All endpoints return JSON. Dates are ISO 8601 strings.

Error responses always follow the shape:
`{ statusCode, message, error, path, timestamp }`
 * OpenAPI spec version: 1.0
 */

export type UpdateTaskDtoStatus = (typeof UpdateTaskDtoStatus)[keyof typeof UpdateTaskDtoStatus];

export const UpdateTaskDtoStatus = {
  todo: 'todo',
  'in-progress': 'in-progress',
  done: 'done',
} as const;
